name: ${COMPOSE_PROJECT_NAME}
services:
  elasticsearch:
    container_name: ${ELASTIC_CONTAINER}
    build:
      context: ./docker-configs/elasticsearch
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    environment:
      - discovery.type=single-node
      - cluster.name=custom-cluster
      - 'ES_JAVA_OPTS=-Xms2048m -Xmx2048m'
    volumes:
      - ${ELASTIC_DATA_DIR}:/usr/share/elasticsearch/data
    networks:
      - backend
      - external_network

  kibana:
    container_name: ${KIBANA_CONTAINER}
    build:
      context: ./docker-configs/kibana
      args:
        KIBANA_VERSION: ${KIBANA_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=http://${ELASTIC_CONTAINER}:${ELASTIC_PORT}
      - SERVER_NAME=${KIBANA_DOMAIN}
      - SERVER_PUBLICBASEURL=http://${KIBANA_DOMAIN}:${KIBANA_PORT}
    depends_on:
      - elasticsearch
    networks:
      - backend

  nginx:
    container_name: ${NGINX_CONTAINER}
    build:
      context: ./docker-configs/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    environment:
      - ELASTIC_CONTAINER=${ELASTIC_CONTAINER}
      - KIBANA_CONTAINER=${KIBANA_CONTAINER}
      - ELASTIC_PORT=${ELASTIC_PORT}
      - KIBANA_PORT=${KIBANA_PORT}
      - ELASTIC_DOMAIN=${ELASTIC_DOMAIN}
      - KIBANA_DOMAIN=${KIBANA_DOMAIN}
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - kibana
    networks:
      - backend

networks:
  backend:
    driver: bridge
  external_network:
    name: ${EXTERNAL_NETWORK}
    external: true
